services:
  app:
    image: ghcr.io/alterleo/demo_devops1:latest
    container_name: app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - ENV=production

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro